--- #YAML:1.0
name:                     CPAN-Testers-WWW-Reports-Mailer
version:                  0.26
abstract:                 CPAN Testers Reports Mailer toolset
author:
  - Barbie <barbie@cpan.org>

license:                  perl
distribution_type:        module
installdirs:              site

requires:
  Cwd:                    0
  CPAN::DistnameInfo:     0
  Class::Accessor::Fast:  0
  DBD::SQLite:            1.07
  DBI:                    0
  Email::Simple:          0
  File::Basename:         0
  File::Path:             0
  Getopt::Long:           0
  MIME::Base64:           0
  MIME::QuotedPrint:      0
  Net::NNTP:              0
  version:                0
recommends:
  Test::More:             0.70
  Test::MockObject:       0
  Test::Pod:              1.00
  Test::Pod::Coverage:    0.08
  Test::CPAN::Meta:       0.12
build_requires:
  Test::More:             0.01

provides:
  CPAN::Testers::WWW::Reports::Mailer:
    file:     lib/CPAN/Testers/WWW/Reports/Mailer.pm
    version:  0.01
  CPAN::Testers::WWW::Reports::Mailer::DBUtils:
    file:     lib/CPAN/Testers/WWW/Reports/Mailer/DBUtils.pm
    version:  0.01

no_index:
  directory:
    - t
    - examples

resources:
  license:    http://dev.perl.org/licenses/
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=CPAN-Testers-WWW-Reports-Mailer

meta-spec:
   version:   1.4
   url:       http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: Hand 1.0
